---

- name: config ssh key pub git
  template:
    src: "{{ item }}"
    dest: "/home/ec2-user/.ssh/id_rsa.pub"
    owner: ec2-user
    group: ec2-user
    mode: 0644
  with_fileglob:
    - "templates/id_rsa_public.j2"
  become: true

- name: config ssh key private git
  template:
    src: "{{ item }}"
    dest: "/home/ec2-user/.ssh/id_rsa"
    owner: ec2-user
    group: ec2-user
    mode: 0600
  with_fileglob:
    - "templates/id_rsa.j2"
  become: true
  notify:
    - Reload ssh

- name: verify known_hosts
  shell: >
    ssh-keyscan -H github.com >> ~/.ssh/known_hosts