---

- name: config ssh key pub git
  template:
    src: "{{ item }}"
    dest: "{{ path_project }}/.env"
    owner: ec2-user
    group: ec2-user
    mode: 0664
  with_fileglob:
    - "templates/env.j2"
  become: true